# Dependencies
markdown:	redcarpet
pygments:	true

# Permalinks
permalink:	/blog/:title

# Setup
title:		BlackImpl's Blog
tagline:	'blog'
description:	'My personal blog.'
url:		http://blackimpl.com

author:
  name:		'BlackImpl'
  url:		https://github.com/blackimpl

paginate:	5

# Custom vars
icon:		/assets/images/icon.png
cover:		/assets/images/cover.jpg

social:
  - icon:	github
    url:	https://github.com/blackimpl
    desc:	Fork me on github

  - icon:	twitter
    url:	https://twitter.com/blackimpl
    desc:	Follow me on twitter

menu:
  - title:	Home
    url:	/

  - title:	About
    url:	/about

copyright:
  author:	BlackImpl
  url:		http://blackimpl.com
  type_title:	Some rights reserved
  type_url:	http://blackimpl.com
